version: "2"

networks:
  thesis:

services:
  orderer.thesis.com:
    container_name: orderer.thesis.com
    image: hyperledger/fabric-orderer:2.4.1
    dns_search: .
    environment:
      # - ORDERER_GENERAL_LOGLEVEL=info
      # - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - thesis
    volumes:
      - ../../artifacts/channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer.thesis.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer.thesis.com/tls:/var/hyperledger/orderer/tls
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"


  
  orderer2.thesis.com:
    container_name: orderer2.thesis.com
    image: hyperledger/fabric-orderer:2.4.1
    dns_search: .
    environment:
      # - ORDERER_GENERAL_LOGLEVEL=debug
      # - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=8050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 8050:8050
      - 8444:8443
    networks:
      - thesis
    volumes:
      - ../../artifacts/channel/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer2.thesis.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer2.thesis.com/tls:/var/hyperledger/orderer/tls
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"




  orderer3.thesis.com:
    container_name: orderer3.thesis.com
    image: hyperledger/fabric-orderer:2.4.1
    dns_search: .
    environment:
      # - ORDERER_GENERAL_LOGLEVEL=debug
      # - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=9050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 9050:9050
      - 8445:8443
    networks:
      - thesis
    volumes:
      - ../../artifacts/channel/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer3.thesis.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/thesis.com/orderers/orderer3.thesis.com/tls:/var/hyperledger/orderer/tls
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"


