version: '2'

networks:
  thesis:

services:

  ca_nodesing:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nodesing.thesis.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=13054
    ports:
      - "13054:13054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/nodesing:/etc/hyperledger/fabric-ca-server
    container_name: ca.nodesing.thesis.com
    hostname: ca.nodesing.thesis.com
    networks:
      - thesis