
OrdererOrgs:
  - Name: Orderer
    Domain: thesis.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: thayson
    Domain: thayson.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: cohuong
    Domain: cohuong.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1
  

  - Name: nodeaus
    Domain: nodeaus.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: nodeeu
    Domain: nodeeu.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1
  
  - Name: nodejapan
    Domain: nodejapan.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1
  

  - Name: nodesing
    Domain: nodesing.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1
  
  - Name: nodeus
    Domain: nodeus.thesis.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1
