version: "2"

networks:
  thesis:

services:


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - thesis

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - thesis
  peer0.nodeaus.thesis.com:
    container_name: peer0.nodeaus.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=nodeausMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis
      - CORE_PEER_ID=peer0.nodeaus.thesis.com
      - CORE_PEER_ADDRESS=peer0.nodeaus.thesis.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nodeaus.thesis.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nodeaus.thesis.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nodeaus.thesis.com:11051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 11051:11051
    volumes:
      - ./crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer0.nodeaus.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer0.nodeaus.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"



  peer1.nodeaus.thesis.com:
    container_name: peer1.nodeaus.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=nodeausMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis

      - CORE_PEER_ID=peer1.nodeaus.thesis.com
      - CORE_PEER_ADDRESS=peer1.nodeaus.thesis.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nodeaus.thesis.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nodeaus.thesis.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nodeaus.thesis.com:11051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 12051:12051
    volumes:
      - ./crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer1.nodeaus.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer1.nodeaus.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    depends_on:
      - couchdb1
      - logger
    logging:
      driver: fluentd
      options:
        tag: docker.{{.ID}}
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"


  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.nodeaus.thesis.com:11051
      - CORE_PEER_LOCALMSPID=nodeausMSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/nodeausMSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer0.nodeaus.thesis.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer0.nodeaus.thesis.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/nodeaus.thesis.com/peers/peer0.nodeaus.thesis.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/nodeaus.thesis.com/users/Admin@nodeaus.thesis.com/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - thesis
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/nodeaus.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/nodeaus.thesis.com/
      - ./../cohuong/crypto-config/peerOrganizations/cohuong.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/cohuong.thesis.com/
      - ./../orderer/crypto-config/ordererOrganizations/thesis.com/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/thesis.com/

  
  logger:
    container_name: fluentd
    image: dvladnik/fluentd-ui
    ports:
      - "24224:24224"
      - "9292:9292"  
    networks:
      - thesis
    volumes:
      - ./fluentd/log:/fluentd/log
      - ./fluentd/:/fluentd/etc
    environment:
      FLUENTD_CONF: fluentd.conf 

