version: "2"

networks:
  thesis:

services:
  # ca-cohuong:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.cohuong.thesis.com
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cohuong.thesis.com-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.cohuong.thesis.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "8054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/cohuong.thesis.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ./crypto-config/peerOrganizations/cohuong.thesis.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.cohuong.thesis.com
  #   hostname: ca.cohuong.thesis.com
  #   networks:
  #     - thesis

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - thesis

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - thesis

  peer0.cohuong.thesis.com:
    container_name: peer0.cohuong.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=cohuongMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis

      - CORE_PEER_ID=peer0.cohuong.thesis.com
      - CORE_PEER_ADDRESS=peer0.cohuong.thesis.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cohuong.thesis.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cohuong.thesis.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cohuong.thesis.com:10051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 9051:9051
    volumes:
      - ./crypto-config/peerOrganizations/cohuong.thesis.com/peers/peer0.cohuong.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/cohuong.thesis.com/peers/peer0.cohuong.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"


  peer1.cohuong.thesis.com:
    container_name: peer1.cohuong.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=cohuongMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis

      - CORE_PEER_ID=peer1.cohuong.thesis.com
      - CORE_PEER_ADDRESS=peer1.cohuong.thesis.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.cohuong.thesis.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.cohuong.thesis.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cohuong.thesis.com:9051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 10051:10051
    volumes:
      - ./crypto-config/peerOrganizations/cohuong.thesis.com/peers/peer1.cohuong.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/cohuong.thesis.com/peers/peer1.cohuong.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"
  


