version: "2"

networks:
  thesis:

services:


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - thesis

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - thesis
  peer0.nodeus.thesis.com:
    container_name: peer0.nodeus.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=nodeusMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis
      - CORE_PEER_ID=peer0.nodeus.thesis.com
      - CORE_PEER_ADDRESS=peer0.nodeus.thesis.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nodeus.thesis.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nodeus.thesis.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nodeus.thesis.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/nodeus.thesis.com/peers/peer0.nodeus.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/nodeus.thesis.com/peers/peer0.nodeus.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"



  peer1.nodeus.thesis.com:
    container_name: peer1.nodeus.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=nodeusMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis

      - CORE_PEER_ID=peer1.nodeus.thesis.com
      - CORE_PEER_ADDRESS=peer1.nodeus.thesis.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nodeus.thesis.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nodeus.thesis.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nodeus.thesis.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/nodeus.thesis.com/peers/peer1.nodeus.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/nodeus.thesis.com/peers/peer1.nodeus.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    depends_on:
      - couchdb1
    networks:
      - thesis
    extra_hosts:
      - "orderer.thesis.com:130.211.113.30"
      - "orderer2.thesis.com:130.211.113.30"
      - "orderer3.thesis.com:130.211.113.30"
      - "peer0.thayson.thesis.com:130.211.113.30"
      - "peer1.thayson.thesis.com:130.211.113.30"
      - "peer0.cohuong.thesis.com:35.192.101.108"
      - "peer1.cohuong.thesis.com:35.192.101.108"
      - "peer0.nodeaus.thesis.com:34.151.86.206"
      - "peer1.nodeaus.thesis.com:34.151.86.206"
      - "peer0.nodeeu.thesis.com:34.140.196.82"
      - "peer1.nodeeu.thesis.com:34.140.196.82"
      - "peer0.nodejapan.thesis.com:34.85.123.204"
      - "peer1.nodejapan.thesis.com:34.85.123.204"
      - "peer0.nodesing.thesis.com:34.87.92.12"
      - "peer1.nodesing.thesis.com:34.87.92.12"
      - "peer0.nodeus.thesis.com:34.133.136.255"
      - "peer1.nodeus.thesis.com:34.133.136.255"



