version: '2'

networks:
  thesis:

services:

  ca_nodeeu:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nodeeu.thesis.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/nodeeu:/etc/hyperledger/fabric-ca-server
    container_name: ca.nodeeu.thesis.com
    hostname: ca.nodeeu.thesis.com
    networks:
      - thesis