version: "2"

networks:
  thesis:

services:


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - thesis

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - thesis
  peer0.thayson.thesis.com:
    container_name: peer0.thayson.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=thaysonMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis
      - CORE_PEER_ID=peer0.thayson.thesis.com
      - CORE_PEER_ADDRESS=peer0.thayson.thesis.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.thayson.thesis.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.thayson.thesis.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.thayson.thesis.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
      - logger
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/thayson.thesis.com/peers/peer0.thayson.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/thayson.thesis.com/peers/peer0.thayson.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - thesis
    logging:
      driver: fluentd
      options:
        tag: docker.{{.ID}}



  peer1.thayson.thesis.com:
    container_name: peer1.thayson.thesis.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      # - FABRIC_LOGGING_SPEC=DEBUG
      # - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=thaysonMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_thesis

      - CORE_PEER_ID=peer1.thayson.thesis.com
      - CORE_PEER_ADDRESS=peer1.thayson.thesis.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.thayson.thesis.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.thayson.thesis.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.thayson.thesis.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/thayson.thesis.com/peers/peer1.thayson.thesis.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/thayson.thesis.com/peers/peer1.thayson.thesis.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    depends_on:
      - couchdb1
      - logger
    logging:
      driver: fluentd
      options:
        tag: docker.{{.ID}}
    networks:
      - thesis


  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.thayson.thesis.com:7051
      - CORE_PEER_LOCALMSPID=thaysonMSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/thaysonMSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/thayson.thesis.com/peers/peer0.thayson.thesis.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/thayson.thesis.com/peers/peer0.thayson.thesis.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/thayson.thesis.com/peers/peer0.thayson.thesis.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/thayson.thesis.com/users/Admin@thayson.thesis.com/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - thesis
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/thayson.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/thayson.thesis.com/
      - ./../cohuong/crypto-config/peerOrganizations/cohuong.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/cohuong.thesis.com/
      - ./../orderer/crypto-config/ordererOrganizations/thesis.com/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/thesis.com/
      - ./../node_us/crypto-config/peerOrganizations/node_us.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/node_us.thesis.com/
      - ./../node_sing/crypto-config/peerOrganizations/node_sing.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/node_sing.thesis.com/
      - ./../node_japan/crypto-config/peerOrganizations/node_japan.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/node_japan.thesis.com/
      - ./../node_eu/crypto-config/peerOrganizations/node_eu.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/node_eu.thesis.com/
      - ./../node_aus/crypto-config/peerOrganizations/node_aus.thesis.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/node_aus.thesis.com/

  
  logger:
    container_name: fluentd
    image: dvladnik/fluentd-ui
    ports:
      - "24224:24224"
      - "9292:9292"  
    networks:
      - thesis
    volumes:
      - ./fluentd/log:/fluentd/log
      - ./fluentd/:/fluentd/etc
    environment:
      FLUENTD_CONF: fluentd.conf 

