version: '2'

networks:
  thesis:

services:

  ca_nodejapan:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nodejapan.thesis.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=12054
    ports:
      - "12054:12054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/nodejapan:/etc/hyperledger/fabric-ca-server
    container_name: ca.nodejapan.thesis.com
    hostname: ca.nodejapan.thesis.com
    networks:
      - thesis