version: '2'

networks:
  thesis:

services:

  ca_nodeus:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nodeus.thesis.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=14054
    ports:
      - "14054:14054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/nodeus:/etc/hyperledger/fabric-ca-server
    container_name: ca.nodeus.thesis.com
    hostname: ca.nodeus.thesis.com
    networks:
      - thesis